name: product_add_or_edit
description: "A new Flutter package project."
version: 0.0.1
homepage:
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  domain_models: ^0.0.0
  product_repository: ^1.0.0
  flutter_bloc: ^9.1.1
  category_repository: ^1.0.0
  component_library: ^0.0.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
